version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres-db
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - "8081:8080"